export { DashboardPage } from './dashboard'
export { VacanciesPage } from './vacancies'
export { ResumesPage } from './resumes'
export { MatchesPage } from './matches'
export { TasksPage } from './tasks'
export { IntegrationsPage } from './integrations'
